# Generated by Django 2.2 on 2022-05-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20220501_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('course_id', models.CharField(max_length=20, verbose_name='课程编号')),
                ('course_year', models.IntegerField(verbose_name='课程年份')),
                ('course_introduction', models.CharField(default='一门简单易学的课程', max_length=40, verbose_name='课程介绍')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MyUser')),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ManyToManyField(to='user.MyUser')),
            ],
        ),
    ]
