# Generated by Django 2.2 on 2022-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_zip_data',
            field=models.BooleanField(default=False, verbose_name='课程数据'),
        ),
    ]
