# Generated by Django 2.2 on 2022-05-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_zip_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectCourse',
        ),
    ]
