# Generated by Django 2.2 on 2022-05-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220501_1421'),
        ('course', '0003_delete_selectcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MyUser')),
            ],
        ),
    ]
