# Generated by Django 2.2 on 2022-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_selectcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_analysis_zip_data',
            field=models.BooleanField(default=False, verbose_name='分析数据'),
        ),
    ]
