# Generated by Django 2.0.7 on 2022-04-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('introduction', models.CharField(default='I am a normal user', max_length=40, verbose_name='介绍')),
                ('user_avatar', models.URLField(verbose_name='用户头像')),
                ('user_number', models.CharField(max_length=20, verbose_name='学号/教师号/管理员编号')),
                ('user_role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
