# Generated by Django 2.2 on 2022-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='true_name',
            new_name='ture_name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.URLField(default='https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif', verbose_name='用户头像'),
        ),
    ]
